# ALPHA GROUP — SYSTEMATIC SEARCH FOR COORDINATE LIE SUBALGEBRAS
# Searches all spans generated by subsets of B1,...,B16.
# A subset S is a Lie subalgebra iff [Bi,Bj] remains in span(S)
# for every Bi,Bj in S. All calculations use exact SymPy arithmetic.

import sympy as sp
from itertools import combinations
from collections import Counter

# 1. SAME 16 GENERATORS USED IN THE ALPHA ANALYSIS
B = [
sp.Matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]),
sp.Matrix([[0,-1,0,0],[1,0,0,0],[0,0,0,-1],[0,0,1,0]]),
sp.Matrix([[0,0,-1,0],[0,0,0,-1],[1,0,0,0],[0,1,0,0]]),
sp.Matrix([[0,0,0,0],[0,0,0,0],[0,0,1,0],[0,0,0,1]]),
sp.Matrix([[1,0,0,1],[0,1,1,0],[0,-1,0,0],[1,0,0,0]]),
sp.Matrix([[0,0,0,1],[0,0,-1,0],[0,-1,0,0],[1,0,0,0]]),
sp.Matrix([[0,0,0,0],[0,0,0,0],[0,0,0,-1],[0,0,1,0]]),
sp.Matrix([[0,-1,-1,0],[1,0,0,1],[-1,0,0,0],[0,-1,0,0]]),
sp.Matrix([[0,0,-1,0],[0,0,0,-1],[0,0,0,0],[0,0,0,0]]),
sp.Matrix([[0,1,0,0],[-1,0,0,0],[1,0,0,1],[0,1,1,0]]),
sp.Matrix([[0,0,0,0],[0,0,0,0],[0,-1,0,0],[1,0,0,0]]),
sp.Matrix([[0,1,-1,0],[1,0,0,-1],[0,0,0,1],[0,0,-1,0]]),
sp.Matrix([[2,0,0,1],[0,0,1,0],[0,-1,-1,0],[1,0,0,1]]),
sp.Matrix([[1,0,0,0],[0,1,0,0],[0,-1,-1,0],[1,0,0,1]]),
sp.Matrix([[0,0,0,-1],[0,0,1,0],[0,1,-1,0],[1,0,0,-1]]),
sp.Matrix([[0,1,1,0],[-1,0,0,-1],[2,0,0,1],[0,0,1,0]])
]

N = len(B)
A = sp.Matrix.hstack(*[sp.Matrix(list(M)) for M in B])

if N != 16 or A.rank() != 16:
    raise RuntimeError("A base B1,...,B16 deve ter rank 16.")

# 2. EXACT COORDINATES IN THE B BASIS
def coordinates(M):
    y = sp.Matrix(list(sp.simplify(M)))
    sol = sp.linsolve((A, y))
    if sol == sp.EmptySet:
        raise ValueError("Matriz fora do span de B1,...,B16.")
    return tuple(sp.simplify(x) for x in next(iter(sol)))

# 3. COMMUTATOR SUPPORTS
support_mask = [[0]*N for _ in range(N)]

for i in range(N):
    for j in range(i+1, N):
        K = sp.simplify(B[i]*B[j] - B[j]*B[i])
        coeff = coordinates(K)
        mask = 0
        for k, value in enumerate(coeff):
            if sp.simplify(value) != 0:
                mask |= (1 << k)
        support_mask[i][j] = mask
        support_mask[j][i] = mask

# 4. COORDINATE LIE-SUBALGEBRA TEST
def is_closed(mask):
    indices = [i for i in range(N) if mask & (1 << i)]
    for i in indices:
        for j in indices:
            if support_mask[i][j] & ~mask:
                return False
    return True

# 5. ENUMERATE ALL 2^16 - 1 NONEMPTY SUBSETS
subalgebras = []

for mask in range(1, 1 << N):
    if is_closed(mask):
        indices = tuple(i+1 for i in range(N) if mask & (1 << i))
        subalgebras.append((mask, indices))

# 6. BASIC LIE PROPERTIES
def bracket(i, j):
    return sp.simplify(B[i]*B[j] - B[j]*B[i])

def is_abelian(indices):
    for i, j in combinations(indices, 2):
        if bracket(i, j) != sp.zeros(4):
            return False
    return True

def derived_dimension(indices):
    mats = []
    for i, j in combinations(indices, 2):
        K = bracket(i, j)
        if K != sp.zeros(4):
            mats.append(sp.Matrix(list(K)))
    return 0 if not mats else sp.Matrix.hstack(*mats).rank()

def coordinate_center(indices):
    result = []
    for i in indices:
        if all(bracket(i, j) == sp.zeros(4) for j in indices):
            result.append(i+1)
    return tuple(result)

# 7. REPORT
print("="*78)
print("ALPHA GROUP — COORDINATE LIE SUBALGEBRAS OF THE 16-GENERATOR STRUCTURE")
print("="*78)
print(f"Rank = {A.rank()}")
print(f"Total coordinate Lie subalgebras = {len(subalgebras)}")

records = []
for n, (_, indices) in enumerate(subalgebras, 1):
    z = tuple(i-1 for i in indices)
    rec = {
        "id": n,
        "dimension": len(indices),
        "generators": indices,
        "abelian": is_abelian(z),
        "derived_dimension": derived_dimension(z),
        "coordinate_center": coordinate_center(z)
    }
    records.append(rec)
    print(f"S{n:02d} | dim={rec['dimension']:2d} | "
          f"{'ABELIAN' if rec['abelian'] else 'NON-ABELIAN':10s} | "
          f"[h,h] dim={rec['derived_dimension']:2d} | "
          f"Zcoord={rec['coordinate_center']} | "
          f"{indices}")

# 8. THE DISTINGUISHED SECTOR FROM THE ARTICLE
target = (1,2,4,7)
target_mask = sum(1 << (i-1) for i in target)

print("\n" + "="*78)
print("DISTINGUISHED BASIC SECTOR <B1,B2,B4,B7>")
print("="*78)
print(f"Closed = {is_closed(target_mask)}")
print(f"Generators = {target}")

# 9. SUMMARY
dims = Counter(r["dimension"] for r in records)
abelian = sum(r["abelian"] for r in records)

print("\n" + "="*78)
print("SUMMARY")
print("="*78)
print("Distribution by dimension:")
for d in sorted(dims):
    print(f"  dim {d:2d}: {dims[d]}")

print(f"\nAbelian subalgebras:     {abelian}")
print(f"Non-abelian subalgebras: {len(records)-abelian}")

# 10. SAVE A MACHINE-READABLE TEXT REPORT
outfile = "alpha_coordinate_lie_subalgebras_results.txt"
with open(outfile, "w", encoding="utf-8") as f:
    f.write("ALPHA GROUP — COORDINATE LIE SUBALGEBRAS\n")
    f.write(f"Rank: {A.rank()}\n")
    f.write(f"Total: {len(records)}\n\n")
    for r in records:
        f.write(
            f"S{r['id']:02d} | dim={r['dimension']} | "
            f"abelian={r['abelian']} | "
            f"derived_dim={r['derived_dimension']} | "
            f"Zcoord={r['coordinate_center']} | "
            f"generators={r['generators']}\n"
        )

print(f"\nResults saved to: {outfile}")
print("="*78)
