# -*- coding: utf-8 -*-
"""alphagroup_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bK36VcE5nwR6wN3W5vFZby_CqyWAYcnQ
"""

import numpy as np
import matplotlib.pyplot as plt

def runge_kutta_4th_order(f, x0, t0, tf, h):
    num_steps = int((tf - t0) / h) + 1
    t_values = np.linspace(t0, tf, num_steps)
    x_values = np.zeros((num_steps, len(x0)))
    x_values[0] = x0

    for i in range(1, num_steps):
        k1 = h * f(t_values[i-1], x_values[i-1])
        k2 = h * f(t_values[i-1] + 0.5 * h, x_values[i-1] + 0.5 * k1)
        k3 = h * f(t_values[i-1] + 0.5 * h, x_values[i-1] + 0.5 * k2)
        k4 = h * f(t_values[i-1] + h, x_values[i-1] + k3)

        x_values[i] = x_values[i-1] + (k1 + 2*k2 + 2*k3 + k4) / 6

    return t_values, x_values

# Sistema de equações diferenciais com a matriz A contendo tangente e cotangente
def system(t, x):
    theta = np.pi / 2880.0048   # Pode ajustar conforme necessário 2.0048
    A = np.array([
        [1, -1/np.tan(theta), -1*np.tan(theta), 1],
        [1/np.tan(theta), 1, -1, -1*np.tan(theta)],
        [1*np.tan(theta), -1, 1, -1/np.tan(theta)],
        [1, 1*np.tan(theta), 1/np.tan(theta), 1]
    ])
    return np.dot(A, x)

# Condições iniciais e parâmetros
x0 = np.array([1, 1, 1, 1], dtype=float)  # exemplo com quatro variáveis
t0 = 0
tf = 10.0
h = 0.001

# Seção de Poincaré (por exemplo, y = 0)
section_plane = 0

# Executa o mapa de Poincaré no estilo de Hénon
t_values, x_values = runge_kutta_4th_order(system, x0, t0, tf, h)

# Plota os resultados
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.plot(t_values, x_values[:, 0], label='$x_1$')
plt.plot(t_values, x_values[:, 1], label='$x_2$')
plt.plot(t_values, x_values[:, 2], label='$x_3$')
plt.plot(t_values, x_values[:, 3], label='$x_4$')
plt.xlabel('Time')
plt.ylabel('$x$ Values')
plt.legend()
plt.title('System Dynamics')

plt.subplot(1, 2, 2)
plt.scatter(x_values[:, 1], x_values[:, 3], s=5, marker='o')
plt.xlabel('$x_2$')
plt.ylabel('$x_4$')
plt.title('Poincaré Map')
plt.grid(True)

plt.tight_layout()


